--разработване на информационна система за съставяне на компютърни конфигурации
CREATE DATABASE PCPartsStore;
USE PCPartsStore;

CREATE TABLE Processor(
ProcID INT IDENTITY PRIMARY KEY NOT NULL,
ProcName NVARCHAR(40) NOT NULL,
ProcNumber NVARCHAR(30) NOT NULL,
ProcPrice FLOAT NOT NULL,
ProcInStock INT NOT NULL
);

INSERT INTO Processor(ProcName, ProcNumber, ProcPrice, ProcInStock) VALUES ('AMD Ryzen 7 5800X',9898221, 850, 24);
INSERT INTO Processor(ProcName, ProcNumber, ProcPrice, ProcInStock) VALUES ('Intel Core i5-7002', 2123422, 400, 50);
INSERT INTO Processor(ProcName, ProcNumber, ProcPrice, ProcInStock) VALUES ('Intel Core i7-11000K', 2334112, 1200, 10);

CREATE TABLE GPU(
GPUID INT IDENTITY NOT NULL PRIMARY KEY,
GPUName NVARCHAR(40) NOT NULL,
GPUNumber NVARCHAR(30) NOT NULL,
GPUPrice FLOAT NOT NULL,
GPUInStock INT NOT NULL
);

INSERT INTO GPU(GPUName, GPUNumber, GPUPrice, GPUInStock) VALUES ('NVIDIA RTX 3070 8GB',9929123, 900, 21);
INSERT INTO GPU(GPUName, GPUNumber, GPUPrice, GPUInStock) VALUES ('NVIDIA RTX 3060 12GB',1230021, 650, 14);
INSERT INTO GPU(GPUName, GPUNumber, GPUPrice, GPUInStock) VALUES ('NVIDIA GTX 1650 4GB',3221343, 450,26);

CREATE TABLE RAM(
RAMID INT IDENTITY NOT NULL PRIMARY KEY,
RAMName NVARCHAR(40) NOT NULL,
RAMNumber NVARCHAR(30) NOT NULL,
RAMPrice FLOAT NOT NULL,
RAMInStock INT NOT NULL
);

INSERT INTO RAM(RAMName, RAMNumber,RAMPrice,RAMInStock) VALUES ('8 GB DDR4 3200 MHz',843214,80,66);
INSERT INTO RAM(RAMName, RAMNumber,RAMPrice,RAMInStock) VALUES ('32 GB DDR4 3200 MHz',854214,500,30);
INSERT INTO RAM(RAMName, RAMNumber,RAMPrice,RAMInStock) VALUES ('16 GB DDR4 3200 MHz',842214,200,50);

CREATE TABLE SSD(
SSDID INT IDENTITY NOT NULL PRIMARY KEY,
SSDName NVARCHAR(40) NOT NULL,
SSDNumber NVARCHAR(30) NOT NULL,
SSDPrice FLOAT NOT NULL,
SSDInStock INT NOT NULL
);

INSERT INTO SSD(SSDName, SSDNumber, SSDPrice, SSDInStock) VALUES ('256 GB SSD M.2 NVMe',994124,100,80);
INSERT INTO SSD(SSDName, SSDNumber, SSDPrice, SSDInStock) VALUES ('512 GB SSD M.2 NVMe',9912345,300,53);
INSERT INTO SSD(SSDName, SSDNumber, SSDPrice, SSDInStock) VALUES ('1 TB SSD M.2 NVMe',9892123,599,23);

CREATE TABLE MotherBoard(
MBID INT IDENTITY NOT NULL PRIMARY KEY,
MBName NVARCHAR(40) NOT NULL,
MBNumber NVARCHAR(30) NOT NULL,
MBPrice FLOAT NOT NULL,
MBInStock INT NOT NULL
);

INSERT INTO MotherBoard(MBName, MBNumber, MBPrice, MBInStock) VALUES ('ASRock H310CM-DVS', 994124, 86, 23);
INSERT INTO MotherBoard(MBName, MBNumber, MBPrice, MBInStock) VALUES ('MSI A320M-A PRO',912450, 126, 35);
INSERT INTO MotherBoard(MBName, MBNumber, MBPrice, MBInStock) VALUES ('ASRock H310CM-HDV',945414,116,23);

CREATE TABLE Config(
ConfigureID INT IDENTITY PRIMARY KEY NOT NULL, 
ConfigName NVARCHAR(50) NOT NULL,
CCPUID INT NOT NULL,
FOREIGN KEY (CCPUID) REFERENCES Processor(ProcID),
CGPUID INT NOT NULL,
FOREIGN KEY (CGPUID) REFERENCES GPU(GPUID),
CRAMID INT NOT NULL,
FOREIGN KEY (CRAMID) REFERENCES RAM(RAMID),
CSSDID INT NOT NULL,
FOREIGN KEY (CSSDID) REFERENCES SSD(SSDID),
CMBID INT NOT NULL,
FOREIGN KEY (CMBID) REFERENCES MotherBoard(MBID),
ConfigPrice FLOAT NOT NULL
);

INSERT INTO Config(ConfigName, CCPUID, CGPUID, CRAMID, CSSDID, CMBID,ConfigPrice) VALUES ('Компютър Lenovo Legion T5 Tower',1,1,1,1,1,3349);
INSERT INTO Config(ConfigName, CCPUID, CGPUID, CRAMID, CSSDID, CMBID,ConfigPrice) VALUES ('Компютър Lenovo IdeaCentre 5 Tower',2,2,2,2,2,1890);
INSERT INTO Config(ConfigName, CCPUID, CGPUID, CRAMID, CSSDID, CMBID,ConfigPrice) VALUES ('Компютър Lenovo Legion T5 Tower',3,3,3,3,3,2100);

CREATE TABLE Sales(
SaleID INT IDENTITY PRIMARY KEY NOT NULL,
ConfigID INT NOT NULL,
FOREIGN KEY (ConfigID) REFERENCES Config(ConfigureID),
SDate DATE NOT NULL,
);

INSERT INTO Sales(ConfigID,SDate) VALUES (1,'2022-11-27')
INSERT INTO Sales(ConfigID,SDate) VALUES (1,'2022-11-17')
INSERT INTO Sales(ConfigID,SDate) VALUES (2,'2022-10-2')
INSERT INTO Sales(ConfigID,SDate) VALUES (2,'2022-9-16')
INSERT INTO Sales(ConfigID,SDate) VALUES (3,'2022-8-7')


SELECT AVG(ConfigPrice) AS AvePrice
FROM Config;


SELECT * FROM Config
ORDER BY ConfigPrice;


SELECT ConfigName, CCPUID, CGPUID, CRAMID, CSSDID, CMBID, ConfigPrice,GPUNumber
FROM Config INNER JOIN GPU ON Config.CGPUID= GPU.GPUID
WHERE GPUNumber=9929123


SELECT * FROM Config INNER JOIN  Processor ON  Config.CCPUID = Processor.ProcID  
WHERE ProcName = 'Intel Core i7-11000K' OR ProcName= 'AMD Ryzen 7 5800X' OR ProcName='Intel Core i5-7002'


SELECT AVG(ProcPrice) AS AveProcPrice,AVG(GPUPrice) AS AveGPUPrice,
AVG(RAMPrice) AS AveRAMPrice, AVG(SSDPrice) AS AveSSDPrice,
AVG(MBPrice) AS AveMBPrice
FROM Processor,GPU, RAM, SSD, MotherBoard


SELECT * FROM Config
UPDATE Config
SET ConfigPrice=ConfigPrice-ConfigPrice*20/100


SELECT * FROM GPU
WHERE GPUPRICE>500 AND GPUPRICE<1000


SELECT TOP(2) GPUInStock FROM GPU


SELECT * FROM Processor
UPDATE Processor 
SET ProcName ='Intel ICore 13-3992' WHERE ProcID=1;


DELETE FROM Processor
WHERE ProcID=1;


SELECT * FROM Sales
WHERE SDate BETWEEN '2022-10-27'  AND '2022-11-27'


SELECT * FROM Config INNER JOIN GPU ON Config.CGPUID = GPU.GPUID
WHERE GPUName NOT LIKE 'NVIDIA RTX 3070 8GB';


CREATE PROCEDURE UpdateConfig 
@UpdateID INT,
@Name NVARCHAR,
@CPU INT,
@GPU INT,
@RAM INT,
@SSD INT,
@MB INT,
@Price FLOAT
AS 
UPDATE Config
SET ConfigName=@Name, CCPUID=@CPU, CGPUID=@GPU, CRAMID=@RAM, CSSDID=@SSD, ConfigPrice=@Price, CMBID=@MB
WHERE ConfigureID=@UpdateID

EXEC UpdateConfig 1,'Comp',2,1,2,1,2,2000

SELECT * FROM Config


CREATE PROCEDURE ShowConfig
AS SELECT * FROM Config;

EXEC ShowConfig


CREATE VIEW V_ShowAvePrice AS
SELECT AVG(ProcPrice) AS AveProcPrice,AVG(GPUPrice) AS AveGPUPrice,
 AVG(RAMPrice) AS AveRAMPrice, AVG(SSDPrice) AS AveSSDPrice,
 AVG(MBPrice) AS AveMBPrice
 FROM Processor,GPU, RAM, SSD, MotherBoard

 SELECT * FROM V_ShowAvePrice
